### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by Gio620** [EliMey99/BackOffice#1]
# Lista de cosas por hacer para acceso rápido

- [ ] Modulo de empleados.
     - [ ] Crear empleados
          - [ ] auto-generar contrato al crear
     - [ ] Mostrar ficha de empleados
     - [ ] Editar empleado
     - [ ] Eliminar empleado
- [ ]  Modulo departamento
     - [ ] Crear departamento
     - [ ] ~~mostrar por departamento???~~
     - [ ] Editar departamento
     - [ ] Eliminar departamento
- [ ] Control de acceso _**(Solo acceso a RRHH)**_
- [ ] Base de Datos
